### DISCUSSION TITLE
YAML to Quest (using Ruby)

### DISCUSSION THREAD

**Discussion by KVonGit** [textadventures/quest#1354] [General]
Another Pixie special: https://github.com/ThePix/quest/wiki/YAML-to-Quest-(using-Ruby)

```yml
- Name: Parsing Area
  Desc: The parser isn't here right now. (There must be a glitch somewhere!)
  
- Name: STD IN
  Inside: true
  Desc: This is where all the information flows down into deepest depths of this world.
  South: Parsing Area
  Objs:
    bytes: You count the bytes, then simplify. 69.105 Kilobytes.
    glitch: It's make your head hurt a little when you look into the glitch. (You don't like seeing all the source code.)

```

```xml
  <object name="parsing_area">
      <inherit name="editor_room" />
      <alias>Parsing Area</alias>
      <description><![CDATA[The parser isn't here right now. (There must be a glitch somewhere!)]]></description>
    <exit alias="north" to="std_in">
      <inherit name="northdirection" />
    </exit>
    </object>
    <object name="std_in">
      <inherit name="editor_room" />
      <alias>STD IN</alias>
      <description><![CDATA[This is where all the information flows down into deepest depths of this world.]]></description>
      <inside />
      <object name="bytes">
        <inherit name="editor_object" />
        <alias>bytes</alias>
        <scenery/>
        <description><![CDATA[You count the bytes, then simplify. 69.105 Kilobytes.]]></description>
      </object>
      <object name="glitch">
        <inherit name="editor_object" />
        <alias>glitch</alias>
        <scenery/>
        <description><![CDATA[It's make your head hurt a little when you look into the glitch. (You don't like seeing all the source code.)]]></description>
      </object>
    <exit alias="south" to="parsing_area">
      <inherit name="southdirection" />
    </exit>
  </object>

```
